version: "3.9"

services:
  app:
    build: .
    container_name: stock-tracker-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_KEY=${API_KEY}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - db
    networks:
      - stock-tracker-network

  db:
    image: postgres:13-alpine
    container_name: stock-tracker-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - stock-tracker-network

networks:
  stock-tracker-network:
    driver: bridge

volumes:
  postgres-data:
